# Generated by Django 4.1 on 2022-10-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_delete_watchlist_alter_comment_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='commentBox',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='user_ID',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='author',
            new_name='seller',
        ),
    ]
